@startuml  
left to right direction
actor Игрок as Player

rectangle "Тайны Лесных Костей" {
  Player --> (Начать новую игру)
  Player --> (Бросить кости)
  Player --> (Завершить игру)
  Player --> (Просмотреть статистику)
  Player --> (Сбросить статистику)
  
  (Бросить кости) .> (Подсчет очков) : includes
  (Завершить игру) .> (Определение победителя) : includes
  (Завершить игру) .> (Сохранение статистики) : includes
}
@enduml